//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class depth
    {
        public string symbol { get; set; }
        public string contract_type { get; set; }
        public long ltime { get; set; }
        public int id { get; set; }
        public string asktype { get; set; }
        public Nullable<decimal> depthvalue1 { get; set; }
        public Nullable<decimal> depthvalue2 { get; set; }
        public Nullable<System.DateTime> Stime { get; set; }
    }
}
