//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class MyTestEntities : DbContext
    {
        public MyTestEntities()
            : base("name=MyTestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<kLine> kLine { get; set; }
        public virtual DbSet<stock> stock { get; set; }
        public virtual DbSet<depth> depth { get; set; }
        public virtual DbSet<ticker> ticker { get; set; }
        public virtual DbSet<socketData> socketData { get; set; }
    
        public virtual int spUpdateText(string str, Nullable<int> id)
        {
            var strParameter = str != null ?
                new ObjectParameter("Str", str) :
                new ObjectParameter("Str", typeof(string));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spUpdateText", strParameter, idParameter);
        }
    }
}
