//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ticker
    {
        public string symbol { get; set; }
        public string contract_type { get; set; }
        public long ltime { get; set; }
        public Nullable<decimal> last { get; set; }
        public Nullable<decimal> buy { get; set; }
        public Nullable<decimal> sell { get; set; }
        public Nullable<decimal> higt { get; set; }
        public Nullable<decimal> low { get; set; }
        public Nullable<decimal> vol { get; set; }
        public long contract_id { get; set; }
        public Nullable<decimal> unit_amount { get; set; }
        public Nullable<System.DateTime> Stime { get; set; }
    }
}
